import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SessionProviderWrapper from "./account/SessionProviderWrapper";

import { Navigation } from '@/app/layout/navigation';
import { SynopticumApiClientProviderWrapper } from "./apiClients/synopticum/SynopticumApiClientProviderWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Synopticum Single Page App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <SessionProviderWrapper>
            <SynopticumApiClientProviderWrapper>
            <Navigation/>
            {children}
            </SynopticumApiClientProviderWrapper>
          </SessionProviderWrapper>
      </body>
    </html>
  );
}
